export const categories = [
  { id: "1", name: "Adesivos", icon: "🏷️", color: "#3B82F6" },
  { id: "2", name: "Banners e Lonas", icon: "🚩", color: "#10B981" },
  { id: "3", name: "Fachadas e ACM", icon: "🏢", color: "#F59E0B" },
  { id: "4", name: "Plotagem e Recorte", icon: "✂️", color: "#8B5CF6" },
  { id: "5", name: "Luminosos e Letras", icon: "⚡", color: "#EF4444" },
  { id: "6", name: "Impressão Digital", icon: "🖨️", color: "#6B7280" },
]

export const standardServices = [
  { id: "s1", category: "Banners e Lonas", name: "Banner em Lona 440g", basePricePer: "m²", basePrice: 25, avgDays: 2, formulaType: "area", unit: "m²", active: true },
  { id: "s2", category: "Banners e Lonas", name: "Banner Blackout Dupla Face", basePricePer: "m²", basePrice: 55, avgDays: 3, formulaType: "area", unit: "m²", active: true },
  { id: "s3", category: "Adesivos", name: "Adesivo Impresso Colorido", basePricePer: "m²", basePrice: 45, avgDays: 3, formulaType: "area", unit: "m²", active: true },
  { id: "s4", category: "Adesivos", name: "Adesivo Recortado (Plotter)", basePricePer: "m²", basePrice: 35, avgDays: 2, formulaType: "area_min1m2", unit: "m²", active: true },
  { id: "s5", category: "Fachadas e ACM", name: "Fachada em ACM", basePricePer: "m²", basePrice: 280, avgDays: 10, formulaType: "area", unit: "m²", active: true },
  { id: "s6", category: "Luminosos e Letras", name: "Letra Caixa Acrílico", basePricePer: "unidade", basePrice: 180, avgDays: 7, formulaType: "unit", unit: "un", active: true },
  { id: "s7", category: "Plotagem e Recorte", name: "Plotagem Planta A1", basePricePer: "unidade", basePrice: 12, avgDays: 1, formulaType: "unit", unit: "un", active: true },
  { id: "s8", category: "Adesivos", name: "Envelopamento Veicular Parcial", basePricePer: "m²", basePrice: 380, avgDays: 5, formulaType: "area", unit: "m²", active: true },
]

export const shelfProducts = [
  { id: "p1", category: "Vinil", name: "Vinil Adesivo Branco Fosco", unit: "m²", avgPrice: 18, supplier: null, active: true },
  { id: "p2", category: "Lona", name: "Lona Impressa 440g", unit: "m²", avgPrice: 8, supplier: null, active: true },
  { id: "p3", category: "ACM", name: "ACM 3mm Branco", unit: "m²", avgPrice: 95, supplier: "AlumíniosCorp", active: true },
  { id: "p4", category: "PVC", name: "PVC Expancel 3mm", unit: "m²", avgPrice: 42, supplier: null, active: true },
  { id: "p5", category: "Tinta", name: "Tinta UV para Impressora", unit: "litro", avgPrice: 180, supplier: "TintasPro", active: true },
]

export const mockRequests = [
  {
    id: "r1",
    serviceType: "Banner em Lona 440g",
    category: "Banners e Lonas",
    material: "Lona 440g",
    width: 3.0,
    height: 1.0,
    quantity: 2,
    city: "São Paulo",
    state: "SP",
    deadlineDays: 5,
    description: "Banner para evento corporativo, precisa de acabamento com ilhós",
    status: "open",
    createdAt: "2026-06-01",
    expiresAt: "2026-06-08",
    buyer: "Empresa Alfa Ltda",
    proposalsCount: 3,
  },
  {
    id: "r2",
    serviceType: "Adesivo Impresso Colorido",
    category: "Adesivos",
    material: "Vinil Adesivo",
    width: 1.2,
    height: 0.8,
    quantity: 50,
    city: "Campinas",
    state: "SP",
    deadlineDays: 7,
    description: "Adesivos para identificação de equipamentos",
    status: "open",
    createdAt: "2026-06-02",
    expiresAt: "2026-06-09",
    buyer: "TechEquip Soluções",
    proposalsCount: 1,
  },
  {
    id: "r3",
    serviceType: "Fachada em ACM",
    category: "Fachadas e ACM",
    material: "ACM 3mm",
    width: 5.0,
    height: 1.2,
    quantity: 1,
    city: "São Paulo",
    state: "SP",
    deadlineDays: 15,
    description: "Fachada para loja nova, instalação inclusa se possível",
    status: "open",
    createdAt: "2026-06-02",
    expiresAt: "2026-06-09",
    buyer: "Varejo Express",
    proposalsCount: 0,
  },
]

export const mockProposals = {
  r1: [
    {
      id: "prop1",
      type: "real" as const,
      supplierName: "GráficaPrint SP",
      supplierRating: 4.8,
      supplierReviews: 127,
      priceTotal: 210,
      deliveryDays: 2,
      paymentTerms: "PIX ou boleto",
      notes: "Entregamos com ilhós e canaleta. Arte inclusa se necessário.",
      isNew: false,
      tags: ["menor_prazo"],
    },
    {
      id: "prop2",
      type: "real" as const,
      supplierName: "Visual Comunicação",
      supplierRating: 4.5,
      supplierReviews: 43,
      priceTotal: 180,
      deliveryDays: 4,
      paymentTerms: "PIX à vista",
      notes: "Preço inclui frete para zona sul de SP.",
      isNew: false,
      tags: ["menor_preco"],
    },
    {
      id: "prop3",
      type: "real" as const,
      supplierName: "BannerFlex",
      supplierRating: 0,
      supplierReviews: 0,
      priceTotal: 220,
      deliveryDays: 3,
      paymentTerms: "Cartão ou PIX",
      notes: "Acabamento premium com bastão.",
      isNew: true,
      tags: [],
    },
    {
      id: "est1",
      type: "estimate" as const,
      supplierName: "Referência de mercado",
      supplierRating: 0,
      supplierReviews: 0,
      priceTotal: 150,
      deliveryDays: 2,
      paymentTerms: "—",
      notes: "Preço estimado com base em valores médios de mercado para Banner em Lona 440g (3,0m × 1,0m × 2un).",
      isNew: false,
      tags: [],
    },
  ],
  r3: [
    {
      id: "est2",
      type: "estimate" as const,
      supplierName: "Referência de mercado",
      supplierRating: 0,
      supplierReviews: 0,
      priceTotal: 1680,
      deliveryDays: 10,
      paymentTerms: "—",
      notes: "Preço estimado com base em valores médios de mercado para Fachada em ACM (5,0m × 1,2m).",
      isNew: false,
      tags: [],
    },
  ],
}

export const stats = {
  totalRequests: 128,
  totalProposals: 534,
  totalSuppliers: 87,
  totalUsers: 312,
  requestsToday: 14,
  newUsersToday: 8,
}
